model:
  learning_rate: 1.0e-4
  target: vqgan.models.vqgan.VQModel
  params:
    embed_dim: 64 # 256
    n_embed: 1024
    ddconfig:
      double_z: False
      z_channels: 64 # 256
      resolution: 64 # 64
      in_channels: 3
      out_ch: 3
      ch: 32 # 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: Network.Taming.models.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 30001
        disc_weight: 0.8
        codebook_weight: 1.0


  vq_params:
        sync_nu: 2.0,
        use_learnable_std: True
        replace_freq: 100
        norm: l2
        cb_norm: l2

data:
  dataset: cifar10
  batch_size: 128
  max_epoch: 1
